version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  auth_service:
    image: abdsyed/ci-cd-auth-microservice:latest
    container_name: auth_service
    ports:
      - "8080:8080"
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_PRIVATE_KEY: ${JWT_PRIVATE_KEY}
      JWT_PUBLIC_KEY: ${JWT_PUBLIC_KEY}
    depends_on:
      - postgres

  poll_service:
    image: abdsyed/ci-cd-poll-microservice:latest
    container_name: poll_service
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_PUBLIC_KEY: |
        -----BEGIN PUBLIC KEY-----
        ${JWT_PUBLIC_KEY}
        -----END PUBLIC KEY-----
    depends_on:
      - postgres
    restart: on-failure:3

volumes:
  postgres_data:
