name: Set inventory file and private key.
description: Set inventory file and private key.
inputs:
  secret_key:
    description: Secret key used for SSH to provisioned machine
    required: true
runs:
  using: composite
  steps:
    - name: Fetch machine IP
      shell: bash
      run: |
        terraform -chdir=terraform/infrastructure output -json machine_ip | grep -v "^\[command\]" > machine_ip.json
        tr -d '"' < machine_ip.json > machine_ip.txt

    - name: Set the private key for the provisioned machine
      shell: bash
      run: |
        mkdir -p ~/.ssh
        echo "${{inputs.secret_key}}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Create the inventory file
      shell: bash
      run: |
        echo "[provisioned_machine]" > ansible/inventory.ini
        echo "$(cat machine_ip.txt)" >> ansible/inventory.ini
        cat ansible/inventory.ini
