- name: Install all the necessary modules.
  hosts: provisioned_machine
  become: yes
  tasks:
    - name: Update cache.
      apt:
        update_cache: yes

    - name: Install necessary modules.
      apt:
        name:
          - git
          - curl
          - ca-certificates
        state: present

    - name: Create /etc/apt/keyrings
      file:
        dest: /etc/apt/keyrings
        mode: "0755"
        state: directory

    - name: Download GPG key.
      get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: "0644"
        force: true

    - name: Determine architecture and OS version codename.
      shell: |
        arch=$(dpkg --print-architecture)
        codename=$(. /etc/os-release && echo "$VERSION_CODENAME")
        echo "deb [arch=${arch} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu ${codename} stable"
      register: docker_repo

    - name: Add Docker APT repository to sources list.
      copy:
        dest: /etc/apt/sources.list.d/docker.list
        content: "{{ docker_repo.stdout }}"
        mode: "0644"

    - name: Install necessary docker packages.
      apt:
        update_cache: true
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present

    - name: Ensure Docker is started and enabled.
      service:
        name: docker
        state: started
        enabled: true

    - name: Install pip (Python package manager)
      apt:
        name: python3-pip
        state: present

    - name: Install Docker and Compose SDK for Python
      pip:
        name:
          - docker
          - docker-compose
