- hosts: provisioned_machine
  become: yes
  tasks:
    - name: Pull Docker Image
      docker_image:
        name: nginx
        source: pull

    - name: Run Docker Container
      docker_container:
        name: nginx
        image: nginx
        state: started
        ports:
          - "80:80"
