name: Deploy docker compose

on: workflow_dispatch

jobs:
  deploy-compose:
    runs-on: ubuntu-22.04

    env:
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      ANSIBLE_HOST_KEY_CHECKING: False

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Ansible
        uses: ./.github/actions/setup-ansible
        with:
          rsa_secret_key: ${{secrets.RSA_SECRET_KEY}}

      - name: Bring up docker compose
        working-directory: ansible
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          JWT_PRIVATE_KEY: ${{ secrets.JWT_PRIVATE_KEY }}
          JWT_PUBLIC_KEY: ${{ secrets.JWT_PUBLIC_KEY }}
        run: |
          ansible-playbook run_compose.yml
