name: Destroy the deployed infrastructure

on: workflow_dispatch

jobs:
  destroy:
    runs-on: ubuntu-22.04

    env:
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0

      - name: Initialize terraform
        run: terraform -chdir=terraform/infrastructure init

      - name: Apply Terraform
        run: terraform -chdir=terraform/infrastructure destroy --auto-approve --var="whitelist_ip=${{vars.WHITELIST_IP}}"
