name: Destroy the deployed infrastructure

on: workflow_dispatch

jobs:
  destroy:
    runs-on: ubuntu-22.04

    env:
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Initialize Terraform
        uses: ./.github/actions/initialize-terraform
        with:
          terraform_directory: terraform/infrastructure
          terraform_version: 1.5.0

      - name: Destroy the infrastructure.
        run: terraform -chdir=terraform/infrastructure destroy --auto-approve --var="whitelist_ip=${{vars.WHITELIST_IP}}"
