name: Publish poll microservice container

on:
  push:
    branches:
      - main
    paths:
      - "application/poll/**"
  workflow_dispatch:

jobs:
  publish-poll:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and publish auth microservice image
        uses: ./.github/actions/build-push-image
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          working_directory: application/poll
          image_name: abdsyed/ci-cd-poll-microservice
