name: Publish poll microservice container

on:
  push:
    branches:
      - main
    paths:
      - "application/poll/**"
  workflow_dispatch:

jobs:
  publish-poll:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build docker image
        working-directory: application/poll
        run: |
          docker build -t abdsyed/ci-cd-poll-microservice:latest .

      - name: Push image to docker hub
        working-directory: application/poll
        run: |
          docker push abdsyed/ci-cd-poll-microservice:latest
