name: Deploy docker compose

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      RSA_SECRET_KEY:
        required: true

jobs:
  restart-compose:
    runs-on: ubuntu-22.04

    env:
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      ANSIBLE_HOST_KEY_CHECKING: False

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Ansible
        uses: ./.github/actions/setup-ansible
        with:
          rsa_secret_key: ${{secrets.RSA_SECRET_KEY}}

      - name: Bring up docker compose
        working-directory: ansible
        run: |
          ansible-playbook restart_compose.yml
