name: Deploy the infrastructure

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-22.04

    env:
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Initialize terraform
        run: terraform -chdir=terraform/infrastructure init

      - name: Apply Terraform
        run: terraform -chdir=terraform/infrastructure apply --auto-approve --var="whitelist_ip=${{vars.WHITELIST_IP}}"

      - name: Fetch machine IP
        run: |
          terraform -chdir=terraform/infrastructure output -json machine_ip > machine_ip.json
          tr -d '"' < machine_ip.json > machine_ip.txt
          echo "Machine IP: $(cat machine_ip.txt)"

      - name: Set the private key for the provisioned machine
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.RSA_SECRET_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Create the inventory file
        run: |
          echo "[provisioned_machine]" >> ansible/inventory.ini
          echo "$(cat machine_ip.txt) ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa" >> ansible/inventory.ini
          echo "Inventory: $(cat ansible/inventory.ini)"

      - name: Install Ansible
        run: sudo apt-get update && sudo apt-get install -y ansible

      - name: Run ansible playbook
        run: ansible-playbook -i ansible/inventory.ini ansible/install_docker.yml
